In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# 0 d array
import numpy as np
arr=np.array([34])
print(arr)

[34]


In [5]:
#1 D array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [12]:
#2 d array
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [13]:
# 3 d array
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#creating a 3 d array with two 2d array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [15]:
import numpy as np

a = np.array(43)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
#accessing array element
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])
print(arr[0])

2
1


In [19]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[5] + arr[4])

11


In [26]:
import numpy as np

arr = np.array([[1,2,3,4],[6,7,8,9]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [27]:
#slicing mentioning the end and start 
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])


[2 3 4 5]


In [25]:
#slicing mentioning only end 
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print(arr[:5])


[1 2 3 4 5]


In [24]:
#slicing not mentioning the end and start 
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [23]:
#slicing mentioning only start 
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [28]:
#slicing elements from the begining to index 4
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [29]:
#negative slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [32]:
#determing the step of slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [3]:
#return every other element from the entire array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
